name: Lint and Type Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install languages package dependencies
        run: cd languages && npm ci

      - name: Type check languages package
        run: cd languages && npx tsc --noEmit

      - name: Lint languages package
        run: cd languages && npm run lint
        continue-on-error: true

      - name: Install core package dependencies
        run: npm ci

      - name: Type check core package
        run: npx tsc --noEmit

      - name: Lint core package
        run: npm run lint
        continue-on-error: true
